name: VOD Download Trigger

on:
  repository_dispatch:
    types: [start-download]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Starte Download Skript
        run: |
          # Hier wird dein Skript aufgerufen
          python3 test_downloader.py "${{ github.event.client_payload.url }}"
