name: VOD Download Trigger

on:
  workflow_dispatch:
    inputs:
      vod_url:
        description: 'VOD URL'
        required: true
        default: ''

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Starte Download
        run: echo "Download gestartet für ${{ github.event.inputs.vod_url }}"
