name: Public Download Trigger
on:
  repository_dispatch:
    types: [start-download]

jobs:
  concurrency:
    group: twitch-download
    cancel-in-progress: false
  download:
    runs-on: ubuntu-latest
    concurrency:
      group: twitch-download  # Sorgt dafür, dass nur ein Video gleichzeitig geladen wird
      cancel-in-progress: false # Warteschlange: Der nächste Download startet, wenn der vorherige fertig ist
    steps:
      ...
